# Generated by Django 5.2.6 on 2025-09-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_staff_groups_alter_staff_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
