# Generated by Django 5.2.6 on 2025-09-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_alter_staff_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="licence_number",
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
    ]
